clockworkpi/launcher

Menu/GameShell/10_Settings/Update/__init__.py
Menu/GameShell/10_Settings/Wifi/keyboard.py
sys.py/UI/Emulator/rom_so_confirm_page.py
sys.py/UI/main_screen.py
sys.py/UI/multilabel.py

add round rect on keyboard selector

 fix bug in compare git versions and main_screen's MsgBox

---

Menu/GameShell/10_Settings/About/__init__.py
sys.py/UI/Emulator/fav_list_page.py
sys.py/UI/Emulator/rom_list_page.py
sys.py/UI/main_screen.py
sys.py/UI/multilabel.py

 add uname info

---

Menu/GameShell/Music Player/mpd_spectrum_page.py
sys.py/UI/Emulator/list_item.py
sys.py/UI/Emulator/rom_list_page.py
sys.py/UI/label.py

avoing same font tangles set_bold to others

 remove unused footmsg from mpd_spectrum_page

---

Menu/GameShell/10_Settings/Brightness/brightness_page.py

sync write value plus 1

---

.gitignore
Menu/GameShell/20_Retro Games/MAME/action.config

Reverts clockworkpi/launcher#35

Revert "Respond to user requests"

---

Menu/GameShell/10_Settings/ButtonsLayout/__init__.py

https://forum.clockworkpi.com/t/is-there-anybody-who-uses-gs-with-customized-key-position-of-abxy-buttons/571/

forum#571/Implemented to sync keymap for RetroArch

---

Menu/GameShell/10_Settings/Time/__init__.py
Menu/GameShell/10_Settings/Time/list_item.py
Menu/GameShell/10_Settings/Time/logger.py
Menu/GameShell/10_Settings/Time/myvars.py
Menu/GameShell/10_Settings/Time/pages.py
Menu/GameShell/10_Settings/Time/timezone_lib_list_page.py

Wow, I really don't know why that file was corrupted
Sorry about that :-(

Corrected broken Time binary file

---

Menu/GameShell/PowerOFF/__init__.py

Update __init__.py : adding an image 

---

sys.py/UI/delete_confirm_page.py

Remove typo in the delete screen (saw this deleting in MGBA)
Deleteing ▶️ Deleting

Remove typo and commented code

---

Menu/GameShell/10_Settings/PowerOptions/__init__.py
Menu/GameShell/10_Settings/Storage/__init__.py
Menu/GameShell/10_Settings/Time/list_item.py
Menu/GameShell/10_Settings/Time/timezone_lib_list_page.py
Menu/GameShell/10_Settings/Update/__init__.py
Menu/GameShell/10_Settings/Wifi/keyboard.py
Menu/GameShell/10_Settings/Wifi/net_item.py
Menu/GameShell/10_Settings/Wifi/text_item.py
Menu/GameShell/10_Settings/Wifi/textarea.py
Menu/GameShell/10_Settings/Wifi/wifi_list.py
Menu/GameShell/10_Settings/list_page.py
Menu/GameShell/Music Player/list_item.py
Menu/GameShell/Music Player/mpd_spectrum_page.py
Menu/GameShell/Music Player/music_lib_list_page.py
Menu/GameShell/Music Player/play_list_page.py
Menu/GameShell/TinyCloud/__init__.py
sys.py/UI/Emulator/fav_list_page.py
sys.py/UI/Emulator/list_item.py
sys.py/UI/Emulator/rom_list_page.py
sys.py/UI/above_all_patch.py
sys.py/UI/confirm_page.py
sys.py/UI/constants.py
sys.py/UI/counter_screen.py
sys.py/UI/download_process_page.py
sys.py/UI/label.py
sys.py/UI/main_screen.py
sys.py/UI/multilabel.py
sys.py/UI/scroller.py
sys.py/UI/skin_manager.py
sys.py/UI/untitled_icon.py

This is just an initial pull request for discussion.
If this is the direction we go in there will be many more files updated.

modify skin manager to allow instanced requests

---

Menu/GameShell/10_Settings/Notification/__init__.py
Menu/GameShell/10_Settings/Wifi/wifi_list.py
Menu/GameShell/10_Settings/list_page.py
sys.py/UI/info_page_list_item.py
sys.py/UI/info_page_selector.py
sys.py/UI/skin_manager.py
sys.py/run.py

For version > 1.22
in Menu/Settings, we can control gsnotify to enable or disable it ,and shows the current config values of gsnotify

add control of gsnotify

---

Menu/GameShell/10_Settings/Wifi/wifi_list.py
sys.py/UI/keyboard.py

bug fix in keyboard done KeyDown event
Done callback should be the Uplevel/Parent page's OnReturnBackCb

bug fix,keyboard

---

awesome/rc.lua
awesome/themes/default/theme.lua

awesome config

---

awesome/rc.lua

some windows have no 'class' key in awesome

 awesome config,missing class in table

---

Menu/GameShell/97_Music Player/mpd_spectrum_page.py

mpd_spectrum_page.py

---

sys.py/UI/CommercialSoftwarePackage/__init__.py

`from UI.keys_def  import CurKeys,IsKeyMenuOrB,IsKeyStartOrA`
in 
` KeyDown(self,event):`
use ,IsKeyMenuOrB,IsKeyStartOrA

CommercialSoftwarePackage buttons  swap

---

Menu/GameShell/10_Settings/About/__init__.py
Menu/GameShell/10_Settings/GateWay/__init__.py
Menu/GameShell/10_Settings/LauncherGo/__init__.py
Menu/GameShell/10_Settings/Lima/__init__.py
Menu/GameShell/10_Settings/PowerOptions/__init__.py
Menu/GameShell/10_Settings/Skins/__init__.py
Menu/GameShell/10_Settings/list_page.py
sys.py/UI/above_all_patch.py
sys.py/UI/constants.py
sys.py/UI/icon_pool.py
sys.py/UI/main_screen.py
sys.py/UI/skin_manager.py
sys.py/UI/util_funcs.py
sys.py/config.py
sys.py/run.py

add skins selection menu in Settings
and other small updates

minor update

---

Menu/GameShell/10_Settings/About/__init__.py
sys.py/UI/multi_icon_item.py

 add DrawRect in multi_icon_item

---

Menu/GameShell/20_Retro Games/MAME/action.config
Menu/GameShell/20_Retro Games/MGBA/action.config
Menu/GameShell/20_Retro Games/NESTOPIA/action.config
Menu/GameShell/20_Retro Games/Pcsx/action.config
Menu/GameShell/50_PICO-8/Post-Up.sh
sys.py/config.py

new version 1.25
1.24 is left
Remove all emulators to /home/cpi/apps/Menu/20_Retro\ Games

 launcher forks now 1.25

---

README.md
requirements.txt

[requirements] initial version

---

.gitignore
Menu/GameShell/30_RetroArch.sh
Menu/GameShell/31_CaveStory.sh
Menu/GameShell/50_PICO-8/PICO-8.sh
Menu/GameShell/50_PICO-8/Post-Up.sh
bluetooth_firmware.sh
launcher.sublime-project
load.sh
sys.py/gsnotify/Jobs/00_lowpower.sh
update.sh

Clean up a bunch of `shellcheck` linter errors in the launch shell scripts.
Also adds a SublimeText 3 project file, which might make this repo more accessible, at least for folks using Sublime.

shellcheck cleanup

---

sys.py/UI/skin_manager.py

The new code checks for a config.ini file in the Skin's folder. Then it checks for a "Font_Paths" section where it replaces the default fonts with the names of the new fonts listed in the Config. You will have to add the desired fonts to the truetype folder within the skin folder and update the config to match the fonts you have added. If you remove the existing fonts in that folder, the launcher will not load if there is a problem with the config file.
Note that the system-wide font name variables do not change, but their referenced file does.
The new Config file would look something like this:
[Font_Paths]
varela = Roboto-Black
veramono = Roboto-Regular
noto = Roboto-Bold
notocjk = Roboto-Light
[Colors]
High = #f0ffff
Text = #ffffff
ReadOnlyText = #ffffff
Front = #614f7d
URL = #f0ffff …

Allows for new skin config.ini format(s)

---

Menu/GameShell/50_PICO-8/compkginfo.json

adding the new pico8 version and updating the md5 hash

updating the pic8 to latest version
